"""Pokémon battle engine — pure data, no I/O.

This package contains the pure-Python core: type chart, team parser, formats,
battle state, damage estimation, and the Glicko-2 rating system. It has zero
I/O dependencies and is safe to import anywhere.
"""

from __future__ import annotations

from pokecore import damage, elo, formats, state, teams, type_chart, types
from pokecore.damage import (
    DamageRoll,
    MoveInput,
    PokemonInput,
    Weather,
    calc_damage,
)
from pokecore.elo import GlickoRating, expected_pair, expected_score, rate, rate_pair
from pokecore.formats import (
    GEN9_OU,
    GEN9_RANDOM_BATTLE,
    GEN9_RATED_BATTLE,
    SUPPORTED_FORMATS,
    Format,
    FormatKind,
    get_format,
)
from pokecore.state import BattleState, FieldState, KnownMove, PokemonState
from pokecore.teams import (
    EVSpread,
    IVSpread,
    MoveSlot,
    PokemonSet,
    Team,
    TypeResolver,
    format_team,
    parse_team,
    sprite_id,
)
from pokecore.type_chart import (
    coverage_summary,
    defensive_multiplier,
    is_immune,
    offensive_coverage,
    resists,
    type_multiplier,
    weak_to,
)
from pokecore.types import (
    NATURE_BOOSTS,
    NEUTRAL_NATURES,
    Boosts,
    Category,
    Generation,
    Nature,
    NatureModifier,
    Stat,
    Status,
    Type,
    TypePair,
    clamp,
)

__all__ = [
    "GEN9_OU",
    "GEN9_RANDOM_BATTLE",
    "GEN9_RATED_BATTLE",
    "NATURE_BOOSTS",
    "NEUTRAL_NATURES",
    "SUPPORTED_FORMATS",
    "BattleState",
    "Boosts",
    "Category",
    "DamageRoll",
    "EVSpread",
    "FieldState",
    "Format",
    "FormatKind",
    "Generation",
    "GlickoRating",
    "IVSpread",
    "KnownMove",
    "Level",
    "MoveInput",
    "MoveSlot",
    "Nature",
    "NatureModifier",
    "PokemonInput",
    "PokemonSet",
    "PokemonSet",
    "PokemonState",
    "PokemonState",
    "Stat",
    "Status",
    "Team",
    "Type",
    "TypePair",
    "TypeResolver",
    "Weather",
    "calc_damage",
    "clamp",
    "coverage_summary",
    "damage",
    "defensive_multiplier",
    "elo",
    "expected_pair",
    "expected_score",
    "format_team",
    "formats",
    "get_format",
    "hp_at_level",
    "is_immune",
    "offensive_coverage",
    "parse_team",
    "rate",
    "rate_pair",
    "resists",
    "sprite_id",
    "state",
    "teams",
    "type_chart",
    "type_multiplier",
    "types",
    "weak_to",
]
